Repository AY1920S2-CS2103T-W17-4/main, pull requests merged in 2020-04, with the labels that each got.

#220 Update dg student view
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UsingCheckstyle.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/module-view/AddGroupActivityDiagram.puml
  docs/diagrams/module-view/AddGroupSequenceDiagram.puml
  docs/diagrams/module-view/AddModuleSequenceDiagram.puml
  docs/diagrams/module-view/DeleteGroupSequenceDiagram.puml
  docs/diagrams/module-view/SortAllSequenceDiagram.puml
  docs/diagrams/module-view/SortCommandsClassDiagram.puml
  docs/diagrams/module-view/SortGroupSequenceDiagram.puml
  docs/diagrams/module-view/SortParserActivityDiagram.puml
  docs/images/AddGroupSequenceDiagram.png
  docs/images/AddModuleSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteGroupSequenceDiagram.png
  docs/images/SortAllSequenceDiagram.png
  docs/images/SortCommandsClassDiagram.png
  docs/images/SortParserActivityDiagram.png
Labels: merge.NeedsReview, priority.High

#227 [Fix] Fit over sized statistics and help window on Windows OS
  build.gradle
  claims.png
  list.png
  person.png
  person2.png
  schedule.png
  src/main/java/tatracker/logic/commands/CommandWords.java
  src/main/java/tatracker/ui/HelpWindow.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/StatisticWindow.java
  src/main/java/tatracker/ui/claimstab/ModuleListPanelCopy.java
  src/main/java/tatracker/ui/studenttab/GroupListPanel.java
  src/main/java/tatracker/ui/studenttab/ModuleListPanel.java
  src/main/java/tatracker/ui/studenttab/StudentListPanel.java
  src/main/resources/images/claims_icon.png
  src/main/resources/images/session_icon.png
  src/main/resources/images/student_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: merge.NeedsReview, priority.High, severity.High, type.Bug

#225 Add support for setting pay rate in TaTracker
  src/main/java/tatracker/model/ReadOnlyTaTracker.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/session/Session.java
  src/main/java/tatracker/model/session/UniqueSessionList.java
  src/main/java/tatracker/model/statistic/Statistic.java
  src/main/java/tatracker/model/student/Rating.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/claimstab/ClaimsListPanel.java
  src/test/java/tatracker/model/TaTrackerTest.java
Labels: merge.NeedsReview

#226 Save done sessions
  src/main/java/tatracker/model/session/SessionType.java
  src/main/java/tatracker/storage/JsonSerializableTaTracker.java
  src/test/data/JsonSerializableTaTrackerTest/duplicateStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/invalidStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/typicalStudentsTaTracker.json
Labels: merge.NeedsReview

#229 Add scrolling through UI lists using arrow keys
  src/main/java/tatracker/ui/CommandBox.java
  src/main/java/tatracker/ui/Focusable.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/claimstab/ModuleListPanelCopy.java
  src/main/java/tatracker/ui/sessiontab/SessionListPanel.java
  src/main/java/tatracker/ui/studenttab/GroupListPanel.java
  src/main/java/tatracker/ui/studenttab/ModuleListPanel.java
  src/main/java/tatracker/ui/studenttab/StudentListPanel.java
  src/main/resources/view/ClaimsListPanel.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/SessionListCard.fxml
  src/main/resources/view/StudentListPanel.fxml
Labels: merge.NeedsReview

#233 Fix deleting sessions when deleting modules
  src/main/java/tatracker/model/TaTracker.java
Labels: merge.NeedsReview

#239 [Hotfix] Fix Report + Duplicate Student Issue
  src/main/java/tatracker/model/TaTracker.java
Labels: severity.High, type.Bug

#224 Update edit student command to find students in module groups
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/logic/parser/student/EditStudentCommandParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/student/UniqueStudentList.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/student/EditStudentDescriptorTest.java
  src/test/java/tatracker/logic/parser/TaTrackerParserTest.java
  src/test/java/tatracker/logic/parser/student/EditStudentCommandParserTest.java
  src/test/java/tatracker/model/ModelStub.java
  src/test/java/tatracker/model/student/UniqueStudentListTest.java
  src/test/java/tatracker/testutil/EditStudentDescriptorBuilder.java
  src/test/java/tatracker/testutil/StudentUtil.java
Labels: merge.NeedsReview

#231 Fix filter session command not working
  src/main/java/tatracker/logic/commands/session/FilterSessionCommand.java
  src/main/java/tatracker/logic/parser/session/FilterSessionCommandParser.java
  src/main/java/tatracker/model/session/SessionPredicate.java
Labels: merge.Outdated

#243 Highlight claims
  src/main/java/tatracker/logic/commands/commons/ListCommand.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/ui/claimstab/ClaimsListPanel.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/ListCommandTest.java
Labels: type.Bug

#314 Fix bug in claims tab during list command
  src/main/java/tatracker/logic/commands/CommandResult.java
  src/main/java/tatracker/logic/commands/commons/ListCommand.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/ui/MainWindow.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
Labels: merge.NeedsReview, priority.High, severity.High, type.Bug

#246 Fix arrow keys losing focus of command box
  src/main/java/tatracker/ui/MainWindow.java
  src/main/resources/view/ClaimsListPanel.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/StudentListPanel.fxml
Labels: type.FunctionalityBug

#324 Fix parsing of impossible dates
  src/main/java/tatracker/commons/util/DateTimeUtil.java
Labels: type.FunctionalityBug

#244 Add missing command entries
  src/main/java/tatracker/logic/commands/CommandEntry.java
  src/main/java/tatracker/logic/commands/commons/SetRateCommand.java
  src/main/java/tatracker/logic/commands/student/FilterStudentCommand.java
  src/main/java/tatracker/logic/parser/PrefixDictionary.java
  src/main/java/tatracker/logic/parser/PrefixEntry.java
Labels: type.FunctionalityBug

#341 Add student command tests
  src/main/java/tatracker/logic/commands/DeleteCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/ui/claimstab/ModuleListPanelCopy.java
  src/main/java/tatracker/ui/studenttab/GroupListPanel.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandIntegrationTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/DeleteStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentDescriptorTest.java
  src/test/java/tatracker/model/ModelStub.java
  src/test/java/tatracker/model/rating/RatingTest.java
  src/test/java/tatracker/model/student/MatricTest.java
  src/test/java/tatracker/testutil/TypicalIndexes.java
  src/test/java/tatracker/testutil/TypicalTaTracker.java
  src/test/java/tatracker/testutil/student/StudentBuilder.java
  src/test/java/tatracker/testutil/student/TypicalStudents.java
Labels: merge.NeedsReview

#358 Use done session list instead of all session list
  src/main/java/tatracker/model/statistic/Statistic.java
Labels: merge.Ready, severity.High

#363 Updated UI Color to Blue
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: merge.NeedsReview

#360 [UG] Add new section on generating of reports
  docs/UserGuide.adoc
Labels: merge.NeedsReview

#365 update DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/find/FilterCommandActivityDiagram.puml
  docs/diagrams/find/FilterStudentSequenceDiagram.puml
  docs/diagrams/find/FindCommandClassDiagram.puml
  docs/diagrams/session-view/DoneSessionSequenceDiagram.puml
  docs/images/DoneSessionSequenceDiagram.png
  docs/images/FilterCommandActivityDiagram.png
  docs/images/FilterStudentSequenceDiagram.png
  docs/images/FindCommandClassDiagram.png
  src/main/java/tatracker/logic/commands/session/DoneSessionPredicate.java
  src/main/java/tatracker/logic/commands/session/FilterClaimCommand.java
  src/main/java/tatracker/logic/parser/session/FilterClaimCommandParser.java
Labels: merge.NeedsReview

#370 [DG] Add Overview, Sequence Diagram, and Use Case for Statistic
  docs/DeveloperGuide.adoc
  docs/diagrams/ReportSequenceDiagram.puml
  docs/images/GotoSequenceDiagram.png
  docs/images/ReportSequenceDiagram.png
Labels: merge.NeedsReview

#385 Add PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SyntaxHighlightingActivityDiagram.puml
  docs/images/InvalidInput.png
  docs/images/SyntaxHighlightingActivityDiagram1.png
  docs/images/ValidInput.png
  docs/team/potatocombat.adoc
Labels: merge.NeedsReview
