Repository AY1920S2-CS2103T-W17-4/main, pull requests merged in 2020-03, with the labels that each got.

#84 Add Session Model
  src/main/java/seedu/address/model/session/Session.java
  src/test/java/seedu/address/model/session/InvalidStartEndTimeTest.java
Labels: priority.High

#97 Remove Address field from Student
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Matric.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/UniqueStudentListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#100 [Session] Fix autotest failing right after midnight
  src/test/java/seedu/address/model/session/InvalidStartEndTimeTest.java
Labels: severity.High, type.Bug

#88 Add skeleton for module and group
  src/main/java/seedu/address/model/group/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupNotFoundException.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/module/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleNotFoundException.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: priority.High

#98 Add main parser skeleton
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/CommandWords.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/TaTrackerParser.java
Labels: priority.High

#108 Add Command to add Session
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/UniqueSessionList.java
  src/main/java/seedu/address/model/session/exceptions/DuplicateSessionException.java
  src/main/java/seedu/address/model/session/exceptions/SessionNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#101 [Session] Convert LocalTime to LocalDateTime
  src/main/java/seedu/address/model/session/Session.java
  src/test/java/seedu/address/model/session/InvalidStartEndTimeTest.java
Labels: priority.High

#106 Rework TA-Tracker logic
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/SessionCommandParser.java
  src/main/java/seedu/address/logic/parser/TaTrackerParser.java
  src/test/java/seedu/address/logic/parser/TaTrackerParserTest.java
Labels: priority.High

#107 Add command to delete a module
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ModuleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: merge.Ready, priority.High

#121 Add command to add a group
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: merge.Ready, priority.High

#118 Fix error message for invalid matric
  src/main/java/seedu/address/model/student/Matric.java
Labels: merge.Ready, severity.Medium, type.Bug

#110 Add command to edit students
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/logic/parser/TaTrackerParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaTrackerParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: merge.NeedsReview, priority.High

#122 Add command to delete a group
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/module/Module.java
Labels: merge.Ready, priority.High

#123 Add DeleteSession Command
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/parser/session/DeleteSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/SessionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: priority.High

#124 Fix session commands
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/commands/EditSessionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/AddSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/EditSessionCommandParser.java
  src/main/java/seedu/address/model/session/Session.java
  src/test/java/seedu/address/model/session/InvalidStartEndTimeTest.java
Labels: merge.Ready, severity.High, type.Bug

#141 Add ModelStub for Module
  src/test/java/tatracker/logic/commands/AddStudentCommandTest.java
Labels: merge.Ready, priority.High

#148 Add support for TSS in module
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/session/UniqueSessionList.java
Labels: merge.NeedsReview, priority.High

#143 Package Student, Module, Group and Session commands
  src/main/java/tatracker/logic/commands/EditCommand.java
  src/main/java/tatracker/logic/commands/group/AddGroupCommand.java
  src/main/java/tatracker/logic/commands/group/DeleteGroupCommand.java
  src/main/java/tatracker/logic/commands/module/AddModuleCommand.java
  src/main/java/tatracker/logic/commands/module/DeleteModuleCommand.java
  src/main/java/tatracker/logic/commands/session/AddSessionCommand.java
  src/main/java/tatracker/logic/commands/session/DeleteSessionCommand.java
  src/main/java/tatracker/logic/commands/session/EditSessionCommand.java
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/TaTrackerParser.java
  src/main/java/tatracker/logic/parser/group/AddGroupCommandParser.java
  src/main/java/tatracker/logic/parser/group/DeleteGroupCommandParser.java
  src/main/java/tatracker/logic/parser/group/GroupCommandParser.java
  src/main/java/tatracker/logic/parser/module/AddModuleCommandParser.java
  src/main/java/tatracker/logic/parser/module/DeleteModuleCommandParser.java
  src/main/java/tatracker/logic/parser/module/ModuleCommandParser.java
  src/main/java/tatracker/logic/parser/session/AddSessionCommandParser.java
  src/main/java/tatracker/logic/parser/session/DeleteSessionCommandParser.java
  src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/logic/parser/student/DeleteStudentCommandParser.java
  src/main/java/tatracker/logic/parser/student/EditStudentCommandParser.java
  src/main/java/tatracker/logic/parser/student/StudentCommandParser.java
  src/test/java/tatracker/logic/LogicManagerTest.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/EditStudentDescriptorTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandIntegrationTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/DeleteStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentDescriptorTest.java
  src/test/java/tatracker/logic/parser/AddStudentCommandParserTest.java
  src/test/java/tatracker/logic/parser/DeleteCommandParserTest.java
  src/test/java/tatracker/logic/parser/FindCommandParserTest.java
  src/test/java/tatracker/logic/parser/TaTrackerParserTest.java
  src/test/java/tatracker/logic/parser/student/AddStudentCommandParserTest.java
  src/test/java/tatracker/logic/parser/student/DeleteStudentCommandParserTest.java
  src/test/java/tatracker/logic/parser/student/EditStudentCommandParserTest.java
  src/test/java/tatracker/model/TaTrackerTest.java
  src/test/java/tatracker/model/session/InvalidStartEndTimeTest.java
  src/test/java/tatracker/model/student/EmailTest.java
  src/test/java/tatracker/model/student/NameTest.java
  src/test/java/tatracker/model/student/PhoneTest.java
  src/test/java/tatracker/model/student/StudentTest.java
  src/test/java/tatracker/model/student/UniqueStudentListTest.java
  src/test/java/tatracker/storage/JsonAdaptedStudentTest.java
  src/test/java/tatracker/storage/JsonSerializableTaTrackerTest.java
  src/test/java/tatracker/testutil/EditStudentDescriptorBuilder.java
  src/test/java/tatracker/testutil/StudentUtil.java
  src/test/java/tatracker/testutil/TypicalStudents.java
Labels: merge.Ready, priority.High, type.Task

#120 Add tabs for Student List and Session List
  src/main/java/tatracker/logic/Logic.java
  src/main/java/tatracker/logic/LogicManager.java
  src/main/java/tatracker/logic/commands/session/EditSessionCommand.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/SessionCommandParser.java
  src/main/java/tatracker/model/session/Session.java
  src/main/java/tatracker/model/session/SessionType.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/SessionCard.java
  src/main/java/tatracker/ui/SessionListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SessionListCard.fxml
  src/main/resources/view/SessionListPanel.fxml
  src/test/java/tatracker/model/session/InvalidStartEndTimeTest.java
Labels: merge.Ready, priority.High

#145 Fix missed references in previous refactors
  README.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/team/johndoe.adoc
  src/main/java/tatracker/logic/commands/session/AddSessionCommand.java
  src/main/java/tatracker/logic/commands/session/EditSessionCommand.java
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/group/UniqueGroupList.java
  src/main/java/tatracker/model/module/UniqueModuleList.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableTaTrackerTest/duplicateStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/invalidStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/typicalStudentsTaTracker.json
  src/test/data/JsonTaTrackerStorageTest/invalidAndValidStudentTaTracker.json
  src/test/data/JsonTaTrackerStorageTest/invalidStudentTaTracker.json
  src/test/java/tatracker/logic/commands/student/EditStudentCommandTest.java
  src/test/java/tatracker/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/tatracker/testutil/TypicalStudents.java
Labels: merge.Ready, priority.High, type.Requirement

#153 Add module view details to the developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/module-view/AddGroupActivityDiagram.puml
  docs/diagrams/module-view/AddModuleSequenceDiagram.puml
  docs/diagrams/module-view/DeleteGroupSequenceDiagram.puml
  docs/diagrams/module-view/ModuleModelClassDiagram.puml
  docs/diagrams/module-view/SortCommandsClassDiagram.puml
  docs/diagrams/module-view/SortGroupSequenceDiagram.puml
  docs/diagrams/module-view/SortParserActivityDiagram.puml
  docs/images/AddGroupActivityDiagram.png
  docs/images/AddModuleSequenceDiagram.png
  docs/images/DeleteGroupSequenceDiagram.png
  docs/images/ModuleModelClassDiagram.png
  docs/images/SortCommandsClassDiagram.png
  docs/images/SortGroupSequenceDiagram.png
  docs/images/SortParserActivityDiagram.png
Labels: merge.NeedsReview, priority.High

#159 Fix: Delete associated sessions when deleting a module
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/session/UniqueSessionList.java
Labels: merge.NeedsReview, priority.High

#158 Add Uml Diagrams for Student
  docs/DeveloperGuide.adoc
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/module-view/ModuleModelClassDiagram.puml
  docs/diagrams/student-view/AddStudentSequenceDiagram.puml
  docs/diagrams/student-view/DeleteStudentSequenceDiagram.puml
  docs/diagrams/student-view/StudentModelClassDiagram.puml
  docs/images/AddStudentSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModuleModelClassDiagram.png
  docs/images/StudentModelClassDiagram.png
Labels: priority.High

#161 Update Developer Guide for v1.3
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/SyntaxHighlighting.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/SyntaxHighlighting.png
Labels: priority.High

#152 [Hotfix] Session delete command not enabled in parser
  src/main/java/tatracker/logic/parser/SessionCommandParser.java
Labels: severity.High

#149 [Notification] Add support for System Tray/Notifications
  src/main/java/tatracker/MainApp.java
  src/main/java/tatracker/commons/core/Notification.java
Labels: priority.High

#146 Remove compulsory fields in student
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/model/student/Email.java
  src/main/java/tatracker/model/student/Phone.java
  src/main/java/tatracker/model/student/Student.java
  src/test/java/tatracker/logic/parser/student/AddStudentCommandParserTest.java
  src/test/java/tatracker/model/student/EmailTest.java
  src/test/java/tatracker/model/student/PhoneTest.java
Labels: merge.NeedsReview, priority.High

#168 Update syntax highlighting section in Developer Guide
  docs/DeveloperGuide.adoc
Labels: merge.Ready, priority.High

#155 Add sorting to Sessions
  docs/diagrams/find/FindCommandActivityDiagram.puml
  src/main/java/tatracker/model/session/Session.java
  src/main/java/tatracker/model/session/UniqueSessionList.java
Labels: merge.NeedsReview, priority.High

#178 Refactor Module hierarchy
  src/main/java/tatracker/logic/commands/EditCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/group/UniqueGroupList.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/student/Student.java
  src/main/java/tatracker/model/student/UniqueStudentList.java
  src/main/java/tatracker/model/util/SampleDataUtil.java
  src/main/java/tatracker/storage/JsonAdaptedStudent.java
  src/test/java/tatracker/testutil/StudentBuilder.java
Labels: merge.Ready, priority.High

#179 Refactor Model hierarchy
  src/main/java/tatracker/logic/Logic.java
  src/main/java/tatracker/logic/LogicManager.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
Labels: merge.Ready, priority.High

#182 Add UI support for TSS Claims, Groups and Modules
  src/main/java/tatracker/commons/core/Notification.java
  src/main/java/tatracker/logic/Logic.java
  src/main/java/tatracker/logic/LogicManager.java
  src/main/java/tatracker/logic/commands/group/AddGroupCommand.java
  src/main/java/tatracker/logic/commands/session/DoneSessionCommand.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/group/AddGroupCommandParser.java
  src/main/java/tatracker/logic/parser/module/AddModuleCommandParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/ReadOnlyTaTracker.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/group/GroupType.java
  src/main/java/tatracker/model/session/SessionType.java
  src/main/java/tatracker/model/session/UniqueDoneSessionList.java
  src/main/java/tatracker/ui/ClaimsListPanel.java
  src/main/java/tatracker/ui/GroupCard.java
  src/main/java/tatracker/ui/GroupListPanel.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/ModuleCard.java
  src/main/java/tatracker/ui/ModuleListPanel.java
  src/main/java/tatracker/ui/ModuleListPanelCopy.java
  src/main/java/tatracker/ui/UiManager.java
  src/main/resources/images/icon.png
  src/main/resources/images/tracker.png
  src/main/resources/view/ClaimsListPanel.fxml
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/ModuleListPanelCopy.fxml
  src/test/java/tatracker/commons/util/AppUtilTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
  src/test/java/tatracker/model/TaTrackerTest.java
Labels: merge.NeedsReview, priority.High

#180 Refactor duplicate module getter in Model interface
  src/main/java/tatracker/logic/commands/group/AddGroupCommand.java
  src/main/java/tatracker/logic/commands/group/DeleteGroupCommand.java
  src/main/java/tatracker/logic/commands/module/DeleteModuleCommand.java
  src/main/java/tatracker/logic/parser/group/AddGroupCommandParser.java
  src/main/java/tatracker/logic/parser/group/DeleteGroupCommandParser.java
  src/main/java/tatracker/logic/parser/module/AddModuleCommandParser.java
  src/main/java/tatracker/logic/parser/module/DeleteModuleCommandParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/module/Module.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
Labels: merge.Waiting, priority.High

#186 Fix TaTracker class only being partially deepcopied.
  src/main/java/tatracker/model/TaTracker.java
Labels: severity.High

#183 Refactor TaTracker hierarchy
  src/main/java/tatracker/logic/commands/session/AddSessionCommand.java
  src/main/java/tatracker/logic/commands/session/EditSessionCommand.java
  src/main/java/tatracker/logic/parser/CliSyntax.java
  src/main/java/tatracker/logic/parser/session/AddSessionCommandParser.java
  src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/student/Email.java
  src/main/java/tatracker/model/student/Phone.java
  src/test/java/tatracker/model/student/EmailTest.java
  src/test/java/tatracker/model/student/PhoneTest.java
Labels: merge.Waiting, priority.High

#184 Update AddStudentCommand to enroll student
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/test/java/tatracker/logic/LogicManagerTest.java
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandIntegrationTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
  src/test/java/tatracker/logic/parser/TaTrackerParserTest.java
  src/test/java/tatracker/logic/parser/student/AddStudentCommandParserTest.java
  src/test/java/tatracker/model/ModelManagerTest.java
  src/test/java/tatracker/model/ModelStub.java
  src/test/java/tatracker/testutil/StudentUtil.java
Labels: merge.Waiting, priority.High

#185 Update DeleteStudentCommand to kick students
  src/main/java/tatracker/logic/commands/student/DeleteStudentCommand.java
  src/main/java/tatracker/logic/parser/student/DeleteStudentCommandParser.java
  src/test/java/tatracker/logic/commands/student/DeleteStudentCommandTest.java
  src/test/java/tatracker/logic/parser/student/DeleteStudentCommandParserTest.java
Labels: merge.Waiting, priority.High

#191 Add support for filter
  src/main/java/tatracker/logic/commands/EditCommand.java
  src/main/java/tatracker/logic/commands/FindCommand.java
  src/main/java/tatracker/logic/commands/ListCommand.java
  src/main/java/tatracker/logic/commands/group/AddGroupCommand.java
  src/main/java/tatracker/logic/commands/group/DeleteGroupCommand.java
  src/main/java/tatracker/logic/commands/module/AddModuleCommand.java
  src/main/java/tatracker/logic/commands/module/DeleteModuleCommand.java
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/commands/student/DeleteStudentCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/logic/parser/TaTrackerParser.java
  src/main/java/tatracker/logic/parser/student/EditStudentCommandParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/ReadOnlyTaTracker.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/storage/JsonSerializableTaTracker.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/commands/DeleteCommandTest.java
  src/test/java/tatracker/logic/commands/FindCommandTest.java
  src/test/java/tatracker/logic/commands/ListCommandTest.java
  src/test/java/tatracker/logic/commands/student/AddStudentCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentCommandTest.java
  src/test/java/tatracker/model/ModelManagerTest.java
  src/test/java/tatracker/model/ModelStub.java
  src/test/java/tatracker/model/TaTrackerTest.java
Labels: priority.High

#193 Add Ratings for Students
  src/main/java/tatracker/logic/commands/student/AddStudentCommand.java
  src/main/java/tatracker/logic/commands/student/EditStudentCommand.java
  src/main/java/tatracker/logic/parser/CliSyntax.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/student/AddStudentCommandParser.java
  src/main/java/tatracker/logic/parser/student/EditStudentCommandParser.java
  src/main/java/tatracker/model/student/Rating.java
  src/main/java/tatracker/model/student/Student.java
  src/main/java/tatracker/model/util/SampleDataUtil.java
  src/main/java/tatracker/storage/JsonAdaptedStudent.java
  src/test/data/JsonSerializableTaTrackerTest/duplicateStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/invalidStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/typicalStudentsTaTracker.json
  src/test/java/tatracker/logic/commands/CommandTestUtil.java
  src/test/java/tatracker/logic/parser/ParserUtilTest.java
  src/test/java/tatracker/logic/parser/TaTrackerParserTest.java
  src/test/java/tatracker/logic/parser/student/AddStudentCommandParserTest.java
  src/test/java/tatracker/model/student/RatingTest.java
  src/test/java/tatracker/model/student/StudentTest.java
  src/test/java/tatracker/storage/JsonAdaptedStudentTest.java
  src/test/java/tatracker/testutil/StudentBuilder.java
  src/test/java/tatracker/testutil/TypicalStudents.java
Labels: merge.Ready, priority.High

#194 Update Storage operations
  src/main/java/tatracker/storage/JsonAdaptedGroup.java
  src/main/java/tatracker/storage/JsonAdaptedModule.java
  src/main/java/tatracker/storage/JsonAdaptedSession.java
  src/main/java/tatracker/storage/JsonAdaptedStudent.java
  src/main/java/tatracker/storage/JsonSerializableTaTracker.java
  src/test/data/JsonSerializableTaTrackerTest/duplicateStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/invalidStudentTaTracker.json
  src/test/data/JsonSerializableTaTrackerTest/typicalStudentsTaTracker.json
  src/test/java/tatracker/logic/commands/DeleteCommandTest.java
  src/test/java/tatracker/logic/commands/student/EditStudentCommandTest.java
  src/test/java/tatracker/storage/JsonAdaptedStudentTest.java
  src/test/java/tatracker/storage/JsonSerializableTaTrackerTest.java
  src/test/java/tatracker/storage/JsonTaTrackerStorageTest.java
  src/test/java/tatracker/testutil/EditStudentDescriptorBuilder.java
  src/test/java/tatracker/testutil/StudentUtil.java
  src/test/java/tatracker/testutil/TypicalStudents.java
Labels: merge.NeedsReview, priority.High

#195 Add module sort feature
  src/main/java/tatracker/logic/commands/SortCommand.java
  src/main/java/tatracker/logic/commands/SortGroupCommand.java
  src/main/java/tatracker/logic/commands/SortModuleCommand.java
  src/main/java/tatracker/logic/parser/SortCommandParser.java
  src/main/java/tatracker/logic/parser/TaTrackerParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/student/UniqueStudentList.java
  src/test/java/tatracker/model/ModelStub.java
Labels: merge.NeedsReview, priority.High

#196 Add edit group command
  src/main/java/tatracker/logic/commands/group/EditGroupCommand.java
  src/main/java/tatracker/logic/parser/CliSyntax.java
  src/main/java/tatracker/logic/parser/group/EditGroupCommandParser.java
  src/main/java/tatracker/logic/parser/group/GroupCommandParser.java
  src/main/java/tatracker/model/group/Group.java
Labels: merge.NeedsReview, priority.High

#200 Add function to sort by matric number
  src/main/java/tatracker/logic/commands/SortCommand.java
  src/main/java/tatracker/logic/commands/SortGroupCommand.java
  src/main/java/tatracker/logic/commands/SortModuleCommand.java
  src/main/java/tatracker/logic/commands/group/DeleteGroupCommand.java
  src/main/java/tatracker/logic/commands/module/DeleteModuleCommand.java
  src/main/java/tatracker/logic/commands/student/DeleteStudentCommand.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/group/Group.java
  src/main/java/tatracker/model/module/Module.java
  src/main/java/tatracker/model/student/UniqueStudentList.java
  src/test/java/tatracker/model/ModelStub.java
Labels: merge.NeedsReview, priority.High

#201 Fix isSameStudent comparison
  src/main/java/tatracker/model/student/Student.java
  src/main/java/tatracker/storage/JsonAdaptedGroup.java
  src/main/java/tatracker/storage/JsonAdaptedModule.java
  src/main/java/tatracker/storage/JsonSerializableTaTracker.java
  src/test/java/tatracker/model/student/StudentTest.java
Labels: severity.High, type.Bug

#203 Fix edit group command equals
  src/main/java/tatracker/logic/commands/group/EditGroupCommand.java
Labels: merge.Ready, severity.Medium, type.Bug

#206 Add command to edit a module
  src/main/java/tatracker/logic/commands/group/EditGroupCommand.java
  src/main/java/tatracker/logic/commands/module/EditModuleCommand.java
  src/main/java/tatracker/logic/parser/group/EditGroupCommandParser.java
  src/main/java/tatracker/logic/parser/module/EditModuleCommandParser.java
  src/main/java/tatracker/logic/parser/module/ModuleCommandParser.java
  src/main/java/tatracker/model/Model.java
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/module/Module.java
  src/test/java/tatracker/model/ModelStub.java
Labels: merge.NeedsReview, priority.High

#170 Add Sessions to be recurring sessions
  docs/diagrams/RecurringSession/RecurringSessionsActivityDiagram.puml
  src/main/java/tatracker/logic/commands/session/DeleteSessionCommand.java
  src/main/java/tatracker/logic/commands/session/DoneSessionCommand.java
  src/main/java/tatracker/logic/commands/session/EditSessionCommand.java
  src/main/java/tatracker/logic/parser/CliSyntax.java
  src/main/java/tatracker/logic/parser/session/AddSessionCommandParser.java
  src/main/java/tatracker/logic/parser/session/EditSessionCommandParser.java
  src/main/java/tatracker/model/session/Session.java
  src/main/java/tatracker/storage/JsonAdaptedSession.java
  src/test/java/tatracker/model/session/InvalidStartEndTimeTest.java
Labels: merge.Ready, priority.High

#189 Add GoTo Command
  src/main/java/tatracker/logic/commands/CommandResult.java
  src/main/java/tatracker/logic/commands/ExitCommand.java
  src/main/java/tatracker/logic/commands/GotoCommand.java
  src/main/java/tatracker/logic/commands/HelpCommand.java
  src/main/java/tatracker/logic/parser/GotoCommandParser.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/TaTrackerParser.java
  src/main/java/tatracker/model/tag/Tag.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/tatracker/logic/commands/CommandResultTest.java
  src/test/java/tatracker/logic/commands/ExitCommandTest.java
  src/test/java/tatracker/logic/commands/GotoCommandTest.java
  src/test/java/tatracker/logic/commands/HelpCommandTest.java
Labels: merge.NeedsReview, priority.High, severity.High

#202 Add support to highlight currently shown module and group
  src/main/java/tatracker/model/ModelManager.java
  src/main/java/tatracker/model/TaTracker.java
Labels: merge.NeedsReview, priority.High

#208 Update UG:
  docs/UserGuide.adoc
Labels: merge.NeedsReview, priority.High

#207 Update UG and Relevant Commands
  docs/UserGuide.adoc
  src/main/java/tatracker/logic/commands/group/EditGroupCommand.java
  src/main/java/tatracker/logic/commands/sort/SortCommand.java
  src/main/java/tatracker/logic/commands/sort/SortGroupCommand.java
  src/main/java/tatracker/logic/commands/sort/SortModuleCommand.java
Labels: merge.NeedsReview, priority.High

#213 [Statistic] Generate Statistics in Separate Window
  src/main/java/tatracker/logic/commands/statistic/ShowStatisticCommand.java
  src/main/java/tatracker/logic/commands/statistic/StatisticCommandResult.java
  src/main/java/tatracker/logic/parser/ParserUtil.java
  src/main/java/tatracker/logic/parser/TaTrackerParser.java
  src/main/java/tatracker/logic/parser/statistic/ShowStatisticCommandParser.java
  src/main/java/tatracker/model/ReadOnlyTaTracker.java
  src/main/java/tatracker/model/TaTracker.java
  src/main/java/tatracker/model/session/SessionType.java
  src/main/java/tatracker/model/session/UniqueSessionList.java
  src/main/java/tatracker/model/statistic/Statistic.java
  src/main/java/tatracker/model/student/Rating.java
  src/main/java/tatracker/model/student/UniqueStudentList.java
  src/main/java/tatracker/ui/MainWindow.java
  src/main/java/tatracker/ui/StatisticWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticWindow.fxml
  src/test/java/tatracker/model/TaTrackerTest.java
  src/test/java/tatracker/model/rating/RatingTest.java
Labels: priority.High

#217 Add actual product image
  docs/images/Ui.png
Labels: merge.Ready, priority.High

#215 New user guide skeleton
  docs/UserGuide.adoc
Labels: merge.NeedsReview, priority.High
